source 'https://github.com/cocoapods/specs.git'
platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target '__ProjectName__' do
  pod '__ProjectName__', :path => './'

  target '__ProjectName__Tests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
    pod 'OCMock'
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.3'
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = '$(inherited)'
        end
    end
end

